# Generated by Django 3.1.5 on 2021-04-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
