# Generated by Django 3.1.5 on 2021-04-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210404_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, default='menu.jpg', upload_to='menus-images/'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='slug',
            field=models.SlugField(default='slug', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(default='slug', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
